/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.modelos.ControladorClientes;
import controlador.tda.lista.ListaEnlazada;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author Usuario iTC
 */
public class FrmRegistarCliente extends javax.swing.JFrame {

    private Integer numClientes = 0;
    private final ControladorClientes cc = new ControladorClientes();
    private final ListaEnlazada<Cliente> listaClientes = new ListaEnlazada<>();
    
    //Para Obtener la lista de personas de la base de datos
    //private ListaEnlazada<Cliente> listaClientes = new ClienteDao().listar();

    /**
     * Creates new form FrmRegistarCliente
     */
    public FrmRegistarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCancelarP = new javax.swing.JButton();
        btnModificarP = new javax.swing.JButton();
        txtProvincia = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Propietario"));
        jPanel2.setLayout(null);

        jLabel3.setText("Nombre :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 40, 60, 14);
        jPanel2.add(txtNombre);
        txtNombre.setBounds(120, 40, 130, 30);

        jLabel4.setText("Apellido :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(280, 40, 60, 14);
        jPanel2.add(txtApellido);
        txtApellido.setBounds(350, 40, 130, 30);

        jLabel5.setText("Identificacion :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 90, 80, 14);
        jPanel2.add(txtDireccion);
        txtDireccion.setBounds(350, 90, 130, 30);

        jLabel6.setText("Direccion:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(280, 90, 60, 14);

        jLabel7.setText("Ciudad :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 140, 60, 14);

        jLabel8.setText("Provincia :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(280, 140, 60, 14);

        btnCancelarP.setText("Limpiar");
        btnCancelarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelarP);
        btnCancelarP.setBounds(360, 200, 130, 30);

        btnModificarP.setText("REGISTRAR");
        btnModificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificarP);
        btnModificarP.setBounds(40, 200, 130, 30);
        jPanel2.add(txtProvincia);
        txtProvincia.setBounds(350, 140, 130, 30);
        jPanel2.add(txtIdentificacion);
        txtIdentificacion.setBounds(120, 90, 130, 30);
        jPanel2.add(txtCiudad);
        txtCiudad.setBounds(120, 140, 130, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de Registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPActionPerformed
        // TODO add your handling code here:
        if (txtApellido.getText().equals("") || txtCiudad.getText().equals("") || txtDireccion.getText().equals("") || txtIdentificacion.getText().equals("") || txtNombre.getText().equals("") || txtProvincia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Porfavor rellene todos los datos", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            numClientes++;
            try {
                Integer.valueOf(txtIdentificacion.getText());
                registrar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "La identificacion solo puede contener numeros", "Error", JOptionPane.ERROR_MESSAGE);
            }
            limpiar();
        }

    }//GEN-LAST:event_btnModificarPActionPerformed

    private void btnCancelarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCancelarPActionPerformed

    private void limpiar() {
        txtApellido.setText("");
        txtCiudad.setText("");
        txtDireccion.setText("");
        txtIdentificacion.setText("");
        txtNombre.setText("");
        txtProvincia.setText("");
    }

    private void registrar() {
        try {
            Cliente c = new Cliente();
            c.setId(numClientes);
            c.setNombre(txtNombre.getText());
            c.setApellido(txtApellido.getText());
            c.setCiudad(txtCiudad.getText());
            c.setDireccion(txtDireccion.getText());
            c.setIdentificacion(txtIdentificacion.getText());
            c.setProvincia(txtProvincia.getText());
            
            if (!estaRegistrado()) {
                listaClientes.insertar(c);
                cc.setListaClientes(listaClientes);
                cc.guardarClientes();
            }
            //Para guardar en la base de datos
            //new ClienteDao().guardar(c);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar en base de datos: \n" + ex, "DataBaseError", JOptionPane.ERROR_MESSAGE);
        }
    }

    public Boolean estaRegistrado() {
        try {
            if (listaClientes.buscar("identificacion", txtIdentificacion.getText()).getSize() > 0) {
                JOptionPane.showMessageDialog(null, "Cliente ya existe", "Info", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                return true;
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmRegistarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarP;
    private javax.swing.JButton btnModificarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables

}
